### ISSUE TITLE
Integration with Open Food Facts ?

### ISSUE THREAD

**Issue by teolemon** [Skyost/Beerstory#1]
@Skyost  You could add the possibility to scan beer barcodes with Open Food Facts and contribute missing beers to the database.
We have an official implementation at https://github.com/openfoodfacts/smooth-app as well as a Dart package: https://github.com/openfoodfacts/openfoodfacts-dart

**Comment by Skyost** [comment]
Yes, thanks for the tip ! This app clearly needs a rewrite anyway 😄

**Comment by Skyost** [comment]
Fixed in 1e35723b90a9ddc0037caca109369fd1415c4eee.
